// <auto-generated />
using System;
using Financeiro.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financeiro.Models.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250412193739_Cliente")]
    partial class Cliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oCliente", b =>
                {
                    b.Property<int?>("_IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("_IdPessoa")
                        .HasColumnType("int");

                    b.HasKey("_IdCliente");

                    b.HasIndex("_IdPessoa");

                    b.ToTable("dbCliente");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oEstado", b =>
                {
                    b.Property<int?>("_CodEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_Uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_CodEstado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oMunicipio", b =>
                {
                    b.Property<int?>("_IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("_IdEstado")
                        .HasColumnType("int");

                    b.HasKey("_IdMunicipio");

                    b.HasIndex("_IdEstado");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oPessoa", b =>
                {
                    b.Property<int?>("_IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("_Celular")
                        .HasColumnType("longtext");

                    b.Property<string>("_Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("_Email")
                        .HasColumnType("longtext");

                    b.Property<int?>("_IdMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("_Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("_Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("_Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("_IdPessoa");

                    b.HasIndex("_IdMunicipio");

                    b.ToTable("dbPessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("oPessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oPessoaFisica", b =>
                {
                    b.HasBaseType("Financeiro.Models.Objetos.Cadastros.oPessoa");

                    b.Property<string>("_Apelido")
                        .HasColumnType("longtext");

                    b.Property<string>("_CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("_Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("oPessoaFisica");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oPessoaJuridica", b =>
                {
                    b.HasBaseType("Financeiro.Models.Objetos.Cadastros.oPessoa");

                    b.Property<string>("_CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("_IE")
                        .HasColumnType("longtext");

                    b.Property<string>("_NomeFantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("_RazaoSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("oPessoaJuridica");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oCliente", b =>
                {
                    b.HasOne("Financeiro.Models.Objetos.Cadastros.oPessoa", "_Pessoa")
                        .WithMany()
                        .HasForeignKey("_IdPessoa");

                    b.Navigation("_Pessoa");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oMunicipio", b =>
                {
                    b.HasOne("Financeiro.Models.Objetos.Cadastros.oEstado", "_Estado")
                        .WithMany()
                        .HasForeignKey("_IdEstado");

                    b.Navigation("_Estado");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oPessoa", b =>
                {
                    b.HasOne("Financeiro.Models.Objetos.Cadastros.oMunicipio", "_Municipio")
                        .WithMany()
                        .HasForeignKey("_IdMunicipio");

                    b.Navigation("_Municipio");
                });
#pragma warning restore 612, 618
        }
    }
}
