// <auto-generated />
using Financeiro.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financeiro.Models.Migrations
{
    [DbContext(typeof(_Context))]
    [Migration("20250603192010_criacao")]
    partial class criacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Financeiro.Models.Objetos.Estoque.oCategoriaProduto", b =>
                {
                    b.Property<int>("_IdCategoriaProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_IdCategoriaProduto");

                    b.ToTable("dbCategoriaProduto");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Estoque.oProduto", b =>
                {
                    b.Property<int>("_IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("_Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("_Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("_Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("_EstoqueAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("_EstoqueMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("_IdCategoriaProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("_MargemLucro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("_PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("_UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_IdProduto");

                    b.HasIndex("_IdCategoriaProduto");

                    b.ToTable("dbProduto");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Estoque.oProduto", b =>
                {
                    b.HasOne("Financeiro.Models.Objetos.Estoque.oCategoriaProduto", "_CategoriaProduto")
                        .WithMany()
                        .HasForeignKey("_IdCategoriaProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_CategoriaProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
