// <auto-generated />
using System;
using Financeiro.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financeiro.Models.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oEstado", b =>
                {
                    b.Property<int?>("_CodEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_Uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_CodEstado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oMunicipio", b =>
                {
                    b.Property<int?>("_IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("_IdEstado")
                        .HasColumnType("int");

                    b.HasKey("_IdMunicipio");

                    b.HasIndex("_IdEstado");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("Financeiro.Models.Objetos.Cadastros.oMunicipio", b =>
                {
                    b.HasOne("Financeiro.Models.Objetos.Cadastros.oEstado", "_Estado")
                        .WithMany()
                        .HasForeignKey("_IdEstado");

                    b.Navigation("_Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
